apiVersion: v1
kind: Service
namespace: django-app
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
