apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testapp.fullname" . }}
  labels:
    app: {{ include "testapp.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "testapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "testapp.name" . }}
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: "my-release-postgresql"
            - name: DB_NAME
              value: "tutorial-dev"
              # valueFrom:
              #   secretKeyRef:
              #     name: testapp-db-credentials
              #     key: tutorial-dev
            - name: DB_USER
              value: "admin"
              # valueFrom:
              #   secretKeyRef:
              #     name: testapp-db-credentials
              #     key: admin
            - name: DB_PASS
              value: "123456"
              # valueFrom:
              #   secretKeyRef:
              #     name: testapp-db-credentials
              #     key: "123456"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          command:
            - "sh"
            - "-c"
            - "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3003"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tutorial-volume
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
