apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorial-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast.ru-7a
  volumeMode: Filesystem